### ISSUE TITLE
Hunk start with content on same line

### ISSUE THREAD

**Issue by teacurran** [thombergs/diffparser#2]
Thanks for this library. I've been using it to parse git diff files in one of my projects.
One thing I have come across, is diff files coming from Github and Bitbucket occasionally have the hunk content on the same line as the hunk start. For example:

```
+++ b/lf/src/main/webapp/views/reports/parentletter_es.html
@@ -34,20 +34,20 @@ <h3 class="dr-notification-title">{{noti.title}}</h3>
```

You can see a full example here:
https://github.com/teacurran/sonar-bitbucket/commit/fa978b3d7c0c98ee0bc60c908379fc42dbeae5f4.diff

This causes the parse to fail because it is expecting the line to start and end with @@.

Is this something that you have come across? Is this a different type of diff entirely? Is it something you think the library could or should support?

**Comment by teacurran** [comment]
I forked and made changes that made this work. It's a little sloppy since I am just wrapping my head around the parser. but I'd like to know your thoughts on this.

**Comment by teacurran** [comment]
scratch that. I am seeing more differences between Git and your example patch (I assume SVN). I will look into cloning and copying the parser as it's own parser if I have time this weekend.

**Comment by thombergs** [comment]
Feel free to drop me a pull request with your changes. I will check it out and make another release to the maven repos if it works.
