### ISSUE TITLE
UnifiedDiffParser ignores last Diff if stream does not end with blank line

### ISSUE THREAD

**Issue by ssoloff** [thombergs/diffparser#4]
I observed that if my unified diff file does not end with one or more blank lines, `UnifiedDiffParser` returns a list that does not include the last diff.

The root cause appears to be the lack of transition to the `END` state, which is where the current `Diff` is added to the list of processed `Diff`s.  Adding a blank line to the end of the file forces the transition to the `END` state and produces the expected result.

I've prepared two possible fixes, but I'm not sure which one would be more acceptable to you.

The [first](https://github.com/ssoloff/diffparser/commit/de80658d318f6eefe1453b0706ef8af3b74e54f5) is short and sweet: it simply injects a virtual newline at the end of every stream to ensure the parser always sees a final blank line.  I personally think it smells bad, but it is a very localized change.

The [second](https://github.com/ssoloff/diffparser/commit/14a44bb0d1f7e92c1e64551030b327d33beb512c) modifies the parser states to explicitly process the end-of-stream marker (i.e. a `null` line).  I've only gone so far to ensure that such a marker is recognized as an event that should cause a transition to the `END` state, which solves my immediate problem.  The `ParserState` implementations that currently do not call `matchesEndPattern` could be modified to do so and possibly detect premature termination of the parse, but I feel this is outside the scope of this issue.

Please advise of your preference for how to address this issue, and I'll be happy to submit a PR.

**Comment by thombergs** [comment]
I definitely prefer the first version of the fix, since the code is much easier to understand (even, if is really only a workaround).

**Comment by ssoloff** [comment]
Thanks for the review, Tom.  PR #6 submitted.

**Comment by thombergs** [comment]
just merged it thanks.

Do you need the new version pushed to the maven repos?

**Comment by ssoloff** [comment]
Yes, please, but there's no rush -- whenever you have a chance.  I'm currently using a different library to read unified diffs, but I'd like to switch to `diffparser` in the future because I think it has a cleaner API.

**Comment by thombergs** [comment]
Luckily, a maven release doesn't take too long, once you get the hang of it :).

Version 1.1 is on the way to maven central. It should take 2 hours or so, but I feel it usually takes longer. Just look for it tomorrow.

**Comment by ssoloff** [comment]
Thanks for the quick turnaround, Tom!

**Comment by swalesch** [comment]
just tried ur lib and i encountered that bug again
I used jgit to get a diff as a outputstream, converted that to a String (used it in my code) and back to  an InputStream (would be lovely if ur lib could handle strings or outputstreams)
I got no new Line at the end and it ignors the last hunk, for me it is a quickfix to add just a "\n" at the end, but u may look again into that code.
thx
